/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package database_final;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author victor
 */
public class DireccionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DireccionJPanel
     */
    public DireccionJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_codigoP = new javax.swing.JTextField();
        jTextField_calle = new javax.swing.JTextField();
        jTextField_ciudad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_Save = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jButton_show = new javax.swing.JButton();

        jLabel1.setText("Codigo Postal");

        jLabel2.setText("Calle");

        jLabel3.setText("Ciudad");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo Postal", "Calle", "Ciudad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton_Save.setText("Save");
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        jButton_update.setText("Update");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jButton_clear.setText("Clear");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        jButton_show.setText("Show");
        jButton_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_showActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_codigoP)
                            .addComponent(jTextField_calle)
                            .addComponent(jTextField_ciudad, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_delete)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_Save)
                                    .addComponent(jButton_update))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_show)
                                    .addComponent(jButton_clear)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_codigoP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Save)
                        .addComponent(jButton_clear)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_update)
                    .addComponent(jButton_show))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_delete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:
        try{
            UpdateToDB();
        }catch (SQLException ex){
            Logger.getLogger(Ventas_JPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:
        try{
            SaveToDB();
        }catch (SQLException ex){
            Logger.getLogger(Ventas_JPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        // TODO add your handling code here:
        try{
            Delete();
        }catch (SQLException ex){
            Logger.getLogger(Ventas_JPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_showActionPerformed
        // TODO add your handling code here:
        try{
            ShowData();
        }catch (SQLException ex){
            Logger.getLogger(Ventas_JPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_showActionPerformed

    private Connection con()throws SQLException {
        String usr = "logingui";
        String pss = "1234";
        String url = "jdbc:mysql://localhost:3306/Ferreteria";
        Connection connection = DriverManager.getConnection(url, usr, pss);
        return connection;
    }

    private void SaveToDB() throws SQLException{
        Connection con = con();
        try{
            String query = "INSERT INTO Direcccion VALUES(?,?,?)";
            PreparedStatement st = con.prepareStatement(query);
            st.setInt(1, Integer.parseInt(jTextField_codigoP.getText()));
            st.setString(2, jTextField_calle.getText());
            st.setString(3, jTextField_ciudad.getText());
            st.execute();
            JOptionPane.showMessageDialog(this, "saved");
            st.close();
            con.close();
            Clear();
            ShowData();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void UpdateToDB() throws SQLException{
        Connection con = con();
        try{
            String query = "UPDATE Direcccion "+
                    "SET Calle " + "=IFNULL(?, Calle),"+
                    "Ciudad " + "=  IFNULL(?, Ciudad)"+
                    "WHERE CodigoP = ?";
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1, DefaultStr(jTextField_calle));
            st.setString(2, DefaultStr(jTextField_ciudad));
            st.setObject(3, DefaultInt(jTextField_codigoP));
            st.execute();
            JOptionPane.showMessageDialog(this, "updated");
            st.close();
            con.close();
            Clear();
            ShowData();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }
    private void Delete() throws SQLException {
        Connection con = con();
        try{
            String query= "DELETE FROM Direcccion WHERE CodigoP =?";
            PreparedStatement st = con.prepareStatement(query);
            st.setInt(1, DefaultInt(jTextField_codigoP));
            st.execute();
            JOptionPane.showMessageDialog(this, "deleted");
            st.close();
            con.close();
            Clear();
            ShowData();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }
    private void ShowData() throws SQLException {
        Connection con = con();
        try{
            Statement st = con.createStatement();
            String query = "SELECT * FROM  Direcccion ";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()){
                String codigop = String.valueOf(rs.getInt("CodigoP"));
                String calle = rs.getString("Calle");
                String ciudad = rs.getString("Ciudad");
                String tbData[] ={codigop, calle, ciudad};
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                tblModel.addRow(tbData);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }

    private void Clear(){
        jTextField_codigoP.setText("");
        jTextField_calle.setText("");
        jTextField_ciudad.setText("");
        DefaultTableModel tblModelVentas = (DefaultTableModel)jTable1.getModel();
        tblModelVentas.setRowCount(0);
    }

    private String DefaultStr(JTextField jtf){
        if(jtf.getText().equals(""))
            return null;
        else{
            return jtf.getText();
        }
    }
    private java.lang.Integer DefaultInt(JTextField jtf){
        if(jtf.getText().equals("")){
            return null;
        }
        else{
            return Integer.parseInt(jtf.getText());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Save;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_show;
    private javax.swing.JButton jButton_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_calle;
    private javax.swing.JTextField jTextField_ciudad;
    private javax.swing.JTextField jTextField_codigoP;
    // End of variables declaration//GEN-END:variables
}
