/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package database_final;

/**
 *
 * @author victor
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        productos_JPanel1 = new database_final.Productos_JPanel();
        jButton_Change_user = new javax.swing.JButton();
        jTabbedPane_Homepage = new javax.swing.JTabbedPane();
        ventas_JPanel = new database_final.Ventas_JPanel();
        productos_JPanel = new database_final.Productos_JPanel();
        clientes_JPanel1 = new database_final.Clientes_JPanel();
        proveedor1 = new database_final.Proveedor();
        posicionJPanel1 = new database_final.PosicionJPanel();
        empleados_JPanel1 = new database_final.empleados_JPanel();
        vechiculosJPanel1 = new database_final.VechiculosJPanel();
        sucursalJPanel1 = new database_final.SucursalJPanel();
        direccionJPanel1 = new database_final.DireccionJPanel();
        enviosJPanel1 = new database_final.EnviosJPanel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_Change_user.setText("Change user");
        jButton_Change_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Change_userActionPerformed(evt);
            }
        });

        jTabbedPane_Homepage.addTab("Ventas", ventas_JPanel);
        jTabbedPane_Homepage.addTab("Productos", productos_JPanel);
        jTabbedPane_Homepage.addTab("Clientes", clientes_JPanel1);
        jTabbedPane_Homepage.addTab("Proveedores", proveedor1);
        jTabbedPane_Homepage.addTab("Posicion", posicionJPanel1);
        jTabbedPane_Homepage.addTab("Empleados", empleados_JPanel1);
        jTabbedPane_Homepage.addTab("Vehiculos", vechiculosJPanel1);
        jTabbedPane_Homepage.addTab("Sucursal", sucursalJPanel1);
        jTabbedPane_Homepage.addTab("Direccion", direccionJPanel1);
        jTabbedPane_Homepage.addTab("Envios", enviosJPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jButton_Change_user)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane_Homepage, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTabbedPane_Homepage, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Change_user)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Change_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Change_userActionPerformed
            // TODO add your handling code here:
        dispose();
        Login_form Log_f = new Login_form();
        Log_f.show();
            
    }//GEN-LAST:event_jButton_Change_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private database_final.Clientes_JPanel clientes_JPanel1;
    private database_final.DireccionJPanel direccionJPanel1;
    private database_final.empleados_JPanel empleados_JPanel1;
    private database_final.EnviosJPanel enviosJPanel1;
    private javax.swing.JButton jButton_Change_user;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTabbedPane jTabbedPane_Homepage;
    private database_final.PosicionJPanel posicionJPanel1;
    private database_final.Productos_JPanel productos_JPanel;
    private database_final.Productos_JPanel productos_JPanel1;
    private database_final.Proveedor proveedor1;
    private database_final.SucursalJPanel sucursalJPanel1;
    private database_final.VechiculosJPanel vechiculosJPanel1;
    private database_final.Ventas_JPanel ventas_JPanel;
    // End of variables declaration//GEN-END:variables
}
